export enum FieldType {
  TEXT = 'TEXT',
  PROVINCE = 'PROVINCE',
  COUNTRY = 'COUNTRY',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  DATE = 'DATE',
  FILE_UPLOAD = 'FILE_UPLOAD',
}
