export const givFunAbiInterface = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'tokenAddress',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'creatorAdmin',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'interfaceAdmin',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'creatorRewardRecipient',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'interfaceRewardRecipient',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'positionId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'name',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'symbol',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'int24',
        name: 'startingTickIfToken0IsNewToken',
        type: 'int24',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'metadata',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountTokensBought',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'vaultDuration',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'vaultPercentage',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'msgSender',
        type: 'address',
      },
    ],
    name: 'TokenCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'token0',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'token1',
        type: 'address',
      },
      { indexed: true, internalType: 'uint24', name: 'fee', type: 'uint24' },
      {
        indexed: false,
        internalType: 'int24',
        name: 'tickSpacing',
        type: 'int24',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'pool',
        type: 'address',
      },
    ],
    name: 'PoolCreated',
    type: 'event',
  },
];
